#!/usr/bin/env python3
"""End-to-end: real C client binary -> loopback ps5logd -> run log + manifest.

Run via `make roundtrip` (builds the example) or directly with the binary path
in HELLO_LOG_BIN.
"""

from __future__ import annotations

import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT / "server"))

import ps5logd  # noqa: E402


def build_example(target_dir: Path) -> Path:
    binary = target_dir / "hello_log"
    cc = os.environ.get("CC", "cc")
    subprocess.run([
        cc, "-std=c11", "-O2", "-Wall", "-Wextra", "-Werror", "-pedantic",
        "-I", str(PROJECT / "client"),
        str(PROJECT / "client/examples/hello_log.c"),  # single-header mode: no ps5log.c
        "-o", str(binary),
    ], check=True)
    return binary


class RoundTripTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.tmp = tempfile.TemporaryDirectory(prefix="ps5log-roundtrip-")
        cls.root = Path(cls.tmp.name)
        env_bin = os.environ.get("HELLO_LOG_BIN")
        cls.binary = Path(env_bin) if env_bin else build_example(cls.root)
        if not shutil.which("cc") and not env_bin:
            raise unittest.SkipTest("no C compiler available")

    @classmethod
    def tearDownClass(cls) -> None:
        cls.tmp.cleanup()

    def setUp(self) -> None:
        self.runs = self.root / f"runs-{self._testMethodName}"
        self.out = io.StringIO()
        self.server = ps5logd.Server(ps5logd.RunStore(self.runs),
                                     ps5logd.Printer(stream=self.out, color=False),
                                     bind="127.0.0.1", port=0, udp=True,
                                     udp_idle_seconds=0.3, poll_interval=0.05)
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
        self.thread.start()

    def tearDown(self) -> None:
        self.server.shutdown()
        self.thread.join(timeout=5)

    def write_conf(self, name: str, **extra: object) -> Path:
        conf = self.root / name
        lines = ["# generated by test_roundtrip", f"DEV_SERVER=127.0.0.1",
                 f"DEV_PORT={self.server.port}"]
        lines += [f"{key}={value}" for key, value in extra.items()]
        conf.write_text("\n".join(lines) + "\n")
        return conf

    def manifests(self) -> list[dict]:
        return [json.loads(p.read_text()) for p in sorted(self.runs.glob("*.json"))]

    def wait_manifests(self, count: int, timeout: float = 5.0) -> list[dict]:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            found = self.manifests()
            if len(found) >= count:
                return found
            time.sleep(0.02)
        return self.manifests()

    def run_client(self, conf: Path | None, count: int = 5, env_conf: bool = False,
                   capture: bool = False) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env.pop("PS5LOG_CONF", None)
        env.pop("HELLO_LOG_CAPTURE", None)
        if capture:
            env["HELLO_LOG_CAPTURE"] = "1"
        args = [str(self.binary)]
        if conf is not None and env_conf:
            env["PS5LOG_CONF"] = str(conf)
        elif conf is not None:
            args.append(str(conf))
            args.append(str(count))
        return subprocess.run(args, env=env, cwd=self.root, capture_output=True,
                              text=True, timeout=30)

    def test_tcp_client_run_is_recorded_verbatim(self) -> None:
        conf = self.write_conf("tcp.conf", DEV_TAG="roundtrip")
        proc = self.run_client(conf, count=5)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertIn("capture rc=1 ", proc.stdout)   # capture not requested
        self.assertIn("network=up", proc.stdout)
        manifests = self.wait_manifests(1)
        self.assertEqual(len(manifests), 1)
        manifest = manifests[0]
        self.assertEqual(manifest["title"], "PPSA99999")
        self.assertEqual(manifest["app"], "hello-log")
        self.assertEqual(manifest["identity"]["tag"], "roundtrip")
        self.assertEqual(manifest["transport"], "tcp")
        self.assertEqual(manifest["records"], 9)
        self.assertEqual(manifest["first_seq"], 1)
        self.assertEqual(manifest["last_seq"], 9)
        self.assertEqual(manifest["gaps"], [])
        self.assertTrue(manifest["clean"])
        self.assertEqual(manifest["bye_fields"], {"seq": "9", "reason": "complete"})
        log = (self.runs / manifest["log_path"]).read_text()
        lines = log.splitlines()
        self.assertTrue(lines[0].startswith("HELLO ps5log/1 title=PPSA99999 app=hello-log boot=0x"))
        self.assertIn(" tag=roundtrip", lines[0])
        self.assertTrue(lines[1].endswith("\tMARK\tHELLO_LOG_STARTED"))
        self.assertTrue(lines[2].endswith("\tINFO\tframe=0 flip_arg=0x420000"))
        self.assertTrue(lines[7].endswith("\tINFO\tfence=0x1100"))
        self.assertTrue(lines[8].endswith("\tWARN\texample warning with\ttab and newline"))
        self.assertEqual(lines[-1], "BYE seq=9 reason=complete")
        mono = [int(line.split("\t")[1]) for line in lines[1:-1]]
        self.assertEqual(mono, sorted(mono))

    def test_printf_capture_arrives_as_raw_and_is_restored(self) -> None:
        conf = self.write_conf("capture.conf")
        proc = self.run_client(conf, count=2, capture=True)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        # While captured, the init status line went to the server; the final
        # status line, printed after ps5log_close() restored fd 1, is the only
        # thing on the process's real stdout.
        self.assertEqual(proc.stdout.count("\n"), 1, proc.stdout)
        self.assertIn("hello_log: sent=6", proc.stdout)
        self.assertNotIn("init rc=", proc.stdout)
        manifests = self.wait_manifests(1)
        self.assertEqual(len(manifests), 1)
        manifest = manifests[0]
        self.assertEqual(manifest["records"], 6)
        self.assertEqual(manifest["raw_lines"], 3)
        self.assertEqual(manifest["gaps"], [])
        self.assertTrue(manifest["clean"])
        lines = (self.runs / manifest["log_path"]).read_text().splitlines()
        self.assertTrue(lines[0].startswith("HELLO ps5log/1"))
        self.assertTrue(lines[1].startswith("hello_log: init rc=0 capture rc=0 "), lines[1])
        self.assertTrue(lines[2].endswith("\tMARK\tHELLO_LOG_STARTED"))
        # Raw lines sit exactly between the WARN record and the final MARK:
        # immediate delivery (line buffering took effect) and intact framing
        # when RAW and structured lines share one stream.
        warn_index = next(i for i, line in enumerate(lines) if "\tWARN\t" in line)
        end_index = next(i for i, line in enumerate(lines) if line.endswith("\tMARK\tHELLO_LOG_COMPLETE"))
        self.assertEqual(lines[warn_index + 1:end_index],
                         ["plain printf line 1", "plain stderr line 2"])
        self.assertEqual(lines[-1], "BYE seq=6 reason=complete")
        self.assertNotIn("hello_log: sent=", "\n".join(lines))

    def test_udp_client_run(self) -> None:
        conf = self.write_conf("udp.conf", DEV_UDP=1)
        proc = self.run_client(conf, count=3)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        manifests = self.wait_manifests(1)
        self.assertEqual(len(manifests), 1)
        self.assertEqual(manifests[0]["transport"], "udp")
        self.assertEqual(manifests[0]["records"], 7)
        self.assertTrue(manifests[0]["clean"])
        self.assertEqual(manifests[0]["close_reason"], "bye")

    def test_env_config_path_is_honoured(self) -> None:
        conf = self.write_conf("env.conf")
        proc = self.run_client(conf, env_conf=True)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertIn(f"config={conf}", proc.stdout)
        self.assertEqual(len(self.wait_manifests(1)), 1)

    def test_missing_server_does_not_block_or_crash(self) -> None:
        conf = self.root / "dead.conf"
        conf.write_text("DEV_SERVER=127.0.0.1\nDEV_PORT=1\nDEV_CONNECT_TIMEOUT_MS=300\n")
        started = time.monotonic()
        proc = self.run_client(conf, count=2)
        self.assertLess(time.monotonic() - started, 5.0)
        self.assertEqual(proc.returncode, 1, proc.stdout + proc.stderr)  # nothing sent
        self.assertIn("sent=0", proc.stdout)
        self.assertIn("dropped=6", proc.stdout)
        self.assertEqual(self.manifests(), [])

    def test_no_config_means_disabled(self) -> None:
        proc = self.run_client(None)
        self.assertEqual(proc.returncode, 1, proc.stdout + proc.stderr)
        self.assertIn("config=(none)", proc.stdout)
        self.assertIn("no DEV_SERVER configured", proc.stdout)


if __name__ == "__main__":
    unittest.main()
